version: "3.9"

services:
  postgres_test:
    container_name: postgres_test
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rootroot"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - "5550:5550"
    command:
      -p 5550
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5550" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '27017:27017'